remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme  # Add this line if you already have a plugins list

title: Welcome to the RHSA - Red Hat System Administration Course v2.0
description: Compatible with RHEL 9.x, Rocky Linux 9.x, Alma Linux 9.x, and Euro Linux 9.x
show_downloads: true
